trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureRMServiceConnection: 'terraform'
  environmentName: 'dev'
  tfVersion: '1.7.3'

stages:
  - stage: TerraformPlanAndApply
    displayName: 'Terraform Plan & Apply'
    jobs:
      - job: Terraform
        displayName: 'Terraform Plan and Apply'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

          - task: AzureCLI@1
            displayName: 'Terraform Plan'
            inputs:
              azureSubscription: '$(azureRMServiceConnection)'
              scriptLocation: inlineScript
              inlineScript: |
                echo "##[section]Instalando Terraform $(tfVersion)..."
                curl -sLo terraform.zip https://releases.hashicorp.com/terraform/$(tfVersion)/terraform_$(tfVersion)_linux_amd64.zip
                unzip terraform.zip
                sudo mv terraform /usr/local/bin/
                terraform version

                echo "##[section]Inicializando Terraform..."
                terraform init


          - task: AzureCLI@1
            displayName: 'Terraform Apply'
            inputs:
              azureSubscription: '$(azureRMServiceConnection)'
              scriptLocation: inlineScript
              inlineScript: |
                echo "##[section]Aplicando Terraform Plan..."
                terraform apply -auto-approve tfplan
