trigger:
  branches:
    include:
      - main

pool:
  vmImage: 'ubuntu-latest'

variables:
  azureRMServiceConnection: 'terraform'
  environmentName: 'dev'
  tfVersion: '1.5.7'

stages:
  - stage: TerraformPlanAndApply
    displayName: 'Terraform Plan & Apply'
    jobs:
      - job: Terraform
        displayName: 'Terraform Plan and Apply'
        steps:
          - task: UsePythonVersion@0
            inputs:
              versionSpec: '3.x'
              addToPath: true

   

          - task: AzureCLI@1
            displayName: 'Terraform Apply'
            inputs:
              azureSubscription: '$(azureRMServiceConnection)'
              scriptLocation: inlineScript
              inlineScript: |
                echo "##[section]Aplicando Terraform Plan..."
                terraform apply -auto-approve tfplan
